language: ruby
rvm:
 - ruby-head
 - rbx-2.1.1
 - rbx-head
branches:
   only: master
notifications:
   email: majioa@yandex.ru
before_script: bundle exec rake db:create db:migrate
script: bundle exec rake cucumber
matrix:
   allow_failures:
    - rvm: ruby-head
    - rvm: rbx-head
env:
 - RAILS_ENV=cucumber
