language: ruby
rvm:
 - ruby-head
 - ruby-2.3.0
 - rbx-3.20
branches:
   only: master
notifications:
   email: majioa@yandex.ru
before_script: bundle exec rake db:create db:migrate
script: bundle exec rake cucumber
matrix:
   allow_failures:
    - rvm: ruby-head
    - rvm: ruby-2.3.0
    - rvm: rbx-3.20
env:
 - RAILS_ENV=cucumber
