language: ruby
rvm:
 - ruby-head
 - rbx-2
branches:
   only: master
notifications:
   email: majioa@yandex.ru
before_script: bundle exec rake db:create db:migrate
script: bundle exec rake cucumber
env:
 - RAILS_ENV=cucumber
