---
cucumber:
   adapter: postgresql
   encoding: unicode
   database: dneslov_cucumber
   pool: 5
   username: dneslov
   password: 

development:
   adapter: postgresql
   encoding: unicode
   database: dneslov_development
   pool: 5
   username: dneslov
   password: 
